"""Add encryption changes to Loan model

Revision ID: 880887ffa3f5
Revises: ca47b8a5ba0f
Create Date: 2025-01-18 09:25:44.348443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880887ffa3f5'
down_revision = 'ca47b8a5ba0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.alter_column('monthly_payment',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('interest',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('loan_amount',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.alter_column('loan_amount',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('interest',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('monthly_payment',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
